### ISSUE TITLE
Cannot delete assignments that have opt-outs attached to them

### ISSUE THREAD

**Issue by ben-pr-p** [politics-rewired/Spoke#648]
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
When trying to delete an assignment (by assigning the texter 0 texts in the Texters section of Campaign Edit), the following error is produced:
```
Unhandled rejection error: update or delete on table "assignment" violates foreign key constraint "opt_out_assignment_id_foreign" on table "opt_out"
    at Connection.parseE (/usr/Spoke/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/usr/Spoke/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/usr/Spoke/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**To Reproduce**
1. Upload a campaign
2. Opt out a contact on that campaign via message review, assigning that contact to the supervolunteer that opted it out 
3. Remove that user's texts from the Texters section on the Campaign Edit page
4. Save

**Expected behavior**
We should either:
a) Migrate `opt_out` to have a `user_id` and `campaign_id` instead of an `assignment_id` so that assignments can be deleted no problem
b) Use soft deletes (`assignment.deleted_at`)

**Work around**
In the meantime, keeping an assignment on that campaign for those users by giving them 1 text allows you to make modifications to the other text allocations.

**Comment by ben-pr-p** [comment]
I added not deleting assignments at all a bit ago!
